### ISSUE TITLE
Глобальные переменные окружения эксплойтов

### ISSUE THREAD

**Issue by jnovikov** [jnovikov/neo#1]
Нужно добавить в конфиг сервера возможность указать список переменных, окружения для эксплойта в формате: 

KEY=VALUE

Это может быть полезно для использования написания персистентных эксплойтов (например для указания хоста redis'а)

При запуске соответсвенно передавать данные переменные окружения эксплойту.

**Comment by pomo-mondreganto** [comment]
Added in #5
